feat: :sparkles: create mutation to update user data
Mentor-Cycle/mentor-cycle-be pull request #22
Opened 2023-04-15 19:30 UTC by David-Ackerman

Create mutation on user resolver to alter user data

2023-04-15 19:43 UTC, David-Ackerman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Resolver para editar cadastro](https://trello.com/c/4nuksxEu/72-resolver-para-editar-cadastro)

2023-04-15 20:01 UTC, oliveirabalsa requested changes

2023-04-15 20:01 UTC, oliveirabalsa commented on src/modules/user/user.resolver.ts
> +  }
nesse cenário não iremos setar cookies, essa rota só será para o usuário atualizar seu perfil na tela de "editar meu perfil" o certo seria retornar apenas os dados atualizados

2023-04-15 20:01 UTC, oliveirabalsa commented on src/modules/user/user.repository.ts
> +    input: Omit<Prisma.UserUpdateInput, 'id' | 'isMentor' | 'email'>,
Nesse cenário também teremos que remover a password, pois não será possivel editar através desse fluxo

2023-04-15 20:02 UTC, oliveirabalsa requested changes

2023-04-15 20:02 UTC, oliveirabalsa commented on src/modules/user/user.service.ts
> +import { Exclude } from 'class-transformer';
Está sendo importado e não utilizado

2023-04-15 20:21 UTC, David-Ackerman commented on src/modules/user/user.repository.ts
> +    input: Omit<Prisma.UserUpdateInput, 'id' | 'isMentor' | 'email'>,
Tem outra mutation chamando esse método apenas com a senha, mas retiro a senha na mutation de update antes de chamar esse método

2023-04-19 20:50 UTC, oliveirabalsa approved these changes

2023-04-19 20:51 UTC, merged