[Back-end] - CRUD notificações
Mentor-Cycle/mentor-cycle-be pull request #43
Opened 2023-06-09 19:20 UTC by diegosano

Criado módulo de Notifications (service, resolver, entity, module).

2023-06-10 19:29 UTC, oliveirabalsa requested changes
Aguardando implementação do "readBy"

Colocando apenas para melhor identificação.

2023-06-10 20:47 UTC, diegosano commented
@oliveirabalsa fiz um refactor, e acredito que tenha ficado mais próximo da ideia original, fiquei com medo de performance da gente guardar um array de id de usuários para cada notificação para saber se foi lido ou não.

NotificationData -> guarda as informações do conteúdo, quem criou, data
Notification -> notificação em si, para quem é destinada, se foi lida ou não, e a referência para as informação (NotificationData)

2023-06-11 18:55 UTC, oliveirabalsa approved these changes

2023-06-11 18:55 UTC, oliveirabalsa commented
Show de bola!!!

2023-06-11 19:04 UTC, salviotonon approved these changes

2023-06-12 03:21 UTC, oliveirabalsa commented
@diegosano duas aprovações, ja pode mergear

2023-06-12 12:32 UTC, merged