feat: added testimony crud
Mentor-Cycle/mentor-cycle-be pull request #49
Opened 2023-06-19 17:23 UTC by Peviii

Nesta tarefa eu implementei o CRUD  de Depoimentos da aplicação.

2023-06-20 03:34 UTC, oliveirabalsa commented
@Peviii sua PR não está buildando no pipeline, creio que seja a questão do yarn

2023-06-20 03:35 UTC, oliveirabalsa requested changes
@Peviii sua PR não está buildando no pipeline, creio que seja a questão do yarn

2023-06-20 14:46 UTC, Peviii commented
vou remover o package lock e rodar no yarn, eu tinha posto o package-lock no .gitignore mas não ignorou não sei porque

2023-06-20 22:13 UTC, Peviii commented
consegui rodar o projeto com yarn, porem minha branch esta 2 commits ahead não sei porque

2023-06-24 14:23 UTC, oliveirabalsa approved these changes

2023-06-27 17:38 UTC, merged