feat: create query for all users list
Mentor-Cycle/mentor-cycle-be pull request #52
Opened 2023-06-23 11:44 UTC by 09brsv

Implementei a opção de listar todos os usuários

2023-06-24 14:32 UTC, oliveirabalsa requested changes

2023-06-24 14:32 UTC, oliveirabalsa commented on schema.gql
> +
@09brsv não entendi o pq do novo Type, essa task basicamente fazer um findMany na tabela de user que ja existe, porém, com a possibilidade de aplicar um filtro de firstName, isMentor e Skills.

Hoje já temos uma query que faz um get nos users, porém para mentores. Agora nessa iremos abranger todos os tipos de user(sendo mentor ou não) e também poderemos aplicar filtros de busca como parâmetros da query

2023-06-24 14:32 UTC, oliveirabalsa commented on schema.gql
> +
![image](https://github.com/Mentor-Cycle/mentor-cycle-be/assets/57500163/d8489591-ac22-42f8-96b3-a09411684298)
de uma olhada, nessa query de eventos podemos aplicar um filtro de eventos por aprendiz(learnerId) e eventos por mentor(mentorId)
![image](https://github.com/Mentor-Cycle/mentor-cycle-be/assets/57500163/68c2b367-a075-4905-ab2c-5e110ba49a48)
depois na hora de chamar a função do prisma que busca no banco, a gente passa esses paramentros no "where"

2023-06-25 12:28 UTC, 09brsv commented
Refatorei como solicitado, inserindo os dados no input. 
Sobre o type tbm refatorei mas tive q manter devido ao type FindMentors não ter a propriedade "isMentor"
Antes de reenviar preciso saber se tbm preciso incluir a paginação de orderby e de tamanho da página

2023-06-25 20:37 UTC, oliveirabalsa commented
> Refatorei como solicitado, inserindo os dados no input. Sobre o type tbm refatorei mas tive q manter devido ao type FindMentors não ter a propriedade "isMentor" Antes de reenviar preciso saber se tbm preciso incluir a paginação de orderby e de tamanho da página

Você chegou a subir o código? Aqui não apareceu nenhuma mudança

2023-06-25 21:41 UTC, 09brsv commented
Não subi. Estou aguardando sua resposta pra finalizar.

2023-06-26 00:04 UTC, oliveirabalsa commented
> Não subi. Estou aguardando sua resposta pra finalizar
@09brsv aaah entendi, desculpa cara. Seria interessante sim ter a ordenação, acho que pode manter o mesmo do findMentor, tenta extrair a lógica para uma função externa pra não ter que duplicar

2023-06-27 02:49 UTC, oliveirabalsa approved these changes
Ficou show. Bem organizado, parabéns!

2023-06-27 09:18 UTC, merged